import type { Metadata } from "next";
import { LegalPage } from "@/components/site/LegalPage";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms that govern your use of Zotomic.",
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      updated="August 2026"
      sections={[
        {
          h: "1. Agreement",
          p: [
            "By creating an account or using Zotomic you agree to these terms. If you use Zotomic on behalf of a business, you confirm you are authorised to bind that business.",
          ],
        },
        {
          h: "2. The service",
          p: [
            "Zotomic provides business-intelligence reports, a dashboard, a hosted storefront, and an AI assistant. Features vary by plan and may change over time. Some capabilities depend on third-party accounts you connect.",
          ],
        },
        {
          h: "3. Your responsibilities",
          p: [
            "You are responsible for the accuracy of the data you add or import, for the content and legality of any storefront you publish, for fulfilling orders placed through your storefront, and for keeping your login credentials secure.",
            "You must not use Zotomic to break the law, infringe others' rights, send spam, or attempt to access another tenant's data.",
          ],
        },
        {
          h: "4. AI output",
          p: [
            "Report narratives and assistant responses are generated by an AI model from your calculated figures. They are informational, may contain errors, and are not financial, legal, or tax advice. Verify important numbers against the underlying data before acting.",
          ],
        },
        {
          h: "5. Payments & billing",
          p: [
            "Paid plans are billed per cycle. Payment is confirmed manually: you pay via the method shown on the billing page and submit your transaction reference; access is restored once we confirm it. If payment lapses, your account enters a grace period, then becomes read-only, then locks — your storefront stays live through the read-only stage. See the Refund Policy.",
          ],
        },
        {
          h: "6. Availability",
          p: [
            "We aim for high availability but do not guarantee uninterrupted service. We may perform maintenance and may suspend accounts that violate these terms or put the platform at risk.",
          ],
        },
        {
          h: "7. Termination",
          p: [
            "You may cancel any time from the billing page. We may terminate for material breach. On termination we handle your data as described in the Privacy Policy.",
          ],
        },
        {
          h: "8. Liability",
          p: [
            "To the extent permitted by law, Zotomic is provided “as is” and our liability for any claim is limited to the fees you paid in the three months before the claim.",
          ],
        },
        {
          h: "9. Changes & contact",
          p: ["We may update these terms; continued use after changes means you accept them. Questions: hello@zotomic.com."],
        },
      ]}
    />
  );
}
