import {
  BarChart3,
  Bell,
  BookOpen,
  Boxes,
  CheckCircle2,
  Clock,
  CloudCog,
  Eye,
  FileText,
  Gauge,
  Globe,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  Info,
  Lightbulb,
  type LucideIcon,
  Lock,
  Mail,
  MapPin,
  MessageSquareText,
  Package,
  Palette,
  Phone,
  Rocket,
  Search,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Store,
  Tag,
  Target,
  TrendingUp,
  Truck,
  Users,
  Zap,
} from "lucide-react";

/** Curated icon set used across the marketing-site CMS (nav links, page item cards, footer trust strip). */
export const SITE_ICONS: Record<string, LucideIcon> = {
  BarChart3,
  Bell,
  BookOpen,
  Boxes,
  CheckCircle2,
  Clock,
  CloudCog,
  Eye,
  FileText,
  Gauge,
  Globe,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  Info,
  Lightbulb,
  Lock,
  Mail,
  MapPin,
  MessageSquareText,
  Package,
  Palette,
  Phone,
  Rocket,
  Search,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Store,
  Tag,
  Target,
  TrendingUp,
  Truck,
  Users,
  Zap,
};

export type SiteIconName = keyof typeof SITE_ICONS;
export const SITE_ICON_NAMES = Object.keys(SITE_ICONS) as SiteIconName[];

/** Resolve a stored icon name to a component, with a safe fallback. */
export function siteIcon(name: string | null | undefined): LucideIcon {
  return (name && SITE_ICONS[name]) || Sparkles;
}
