import type { Metadata } from "next";
import { Eye, Lightbulb, Target } from "lucide-react";
import { CtaBand, PageHero, Section } from "@/components/site/marketing";

export const metadata: Metadata = {
  title: "Weekly Intelligence",
  description:
    "A weekly business report that separates fact from interpretation: measured metrics, period-over-period comparison, anomalies, and evidence-backed recommendations.",
};

const BLOCKS = [
  {
    icon: Eye,
    title: "SEE — measured, not guessed",
    text: "Revenue, orders, returns and estimated profit are calculated by deterministic code from your data. When something can't be calculated yet, the report says so instead of showing a zero.",
  },
  {
    icon: Lightbulb,
    title: "UNDERSTAND — why it moved",
    text: "Every metric is compared to the previous comparable period. Anomalies and threshold breaches are flagged, and each insight carries the evidence it's based on plus a confidence level.",
  },
  {
    icon: Target,
    title: "ACT — a short list of next steps",
    text: "Recommendations are tied to the evidence that prompted them and ranked by effort and impact — so you finish the report knowing what to do on Monday.",
  },
];

export default function IntelligencePage() {
  return (
    <>
      <PageHero
        eyebrow="Weekly Intelligence"
        title="The report that tells you what to do"
        subtitle="Sales up but profit down? You'll know in week one — because buying price and marketing cost are part of the math."
      />
      <Section>
        <div className="space-y-4">
          {BLOCKS.map((b) => (
            <div
              key={b.title}
              className="flex gap-4 rounded-lg border border-border bg-surface p-5 shadow-sm"
            >
              <b.icon className="mt-0.5 h-5 w-5 shrink-0 text-primary" />
              <div>
                <p className="text-sm font-bold text-fg">{b.title}</p>
                <p className="mt-1 text-sm text-fg-muted">{b.text}</p>
              </div>
            </div>
          ))}
        </div>
      </Section>
      <Section title="Runs on its own">
        <p className="max-w-2xl text-sm text-fg-muted">
          Reports are generated by a scheduled background job — they don&apos;t need you to keep a
          browser open. If there isn&apos;t enough history yet, the report states exactly what&apos;s
          missing rather than filling the gap with a guess.
        </p>
      </Section>
      <CtaBand />
    </>
  );
}
